#!/usr/bin/env python3
"""Generate static/css/preview-skin.css: survey.css scoped under `.survey-skin` so the Studio's
question test view looks exactly like the respondent survey without restyling the Studio.
Re-run after editing survey.css:  python3 scripts/build_preview_skin.py
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "static", "css", "survey.css")
DST = os.path.join(ROOT, "static", "css", "preview-skin.css")
SKIP = ("html", "body", "main", "header", ".topbar", ".brand", ".hud", ".meta", ".progress", ".teambar",
        ".appnav", "[hidden]", ".overlay", ".tpp-panel", ".celebrate", ".coach", ".toast", ".confetti")


def scope(selector: str) -> str | None:
    sel = selector.strip()
    if not sel or sel.startswith("@") or sel in ("from", "to") or re.fullmatch(r"\d+%", sel):
        return sel
    if sel == ":root":
        return ".survey-skin"
    if any(sel == s or sel.startswith(s + " ") or sel.startswith(s + ".") or sel.startswith(s + ":") for s in SKIP):
        return None
    sel = re.sub(r"^body\.testmode\s+", ".survey-skin.testmode ", sel)
    return ".survey-skin " + sel


def main():
    css = open(SRC, encoding="utf-8").read()
    css = re.sub(r"/\*.*?\*/", "", css, flags=re.S)
    out = []
    # simple tokenizer: handles nested @media/@keyframes blocks
    def emit_block(prelude, body):
        p = prelude.strip()
        if p.startswith("@media") or p.startswith("@supports"):
            inner = build(body)
            if inner.strip():
                out.append(p + "{" + inner + "}")
        elif p.startswith("@keyframes") or p.startswith("@font-face"):
            out.append(p + "{" + body + "}")
        else:
            sels = [scope(s) for s in p.split(",")]
            sels = [s for s in sels if s]
            if sels:
                out.append(",".join(sels) + "{" + body.strip() + "}")

    def build(text):
        res, j, d, pre, start = [], 0, 0, "", 0
        while j < len(text):
            ch = text[j]
            if ch == "{":
                if d == 0:
                    pre = text[start:j]; start = j + 1
                d += 1
            elif ch == "}":
                d -= 1
                if d == 0:
                    body = text[start:j]
                    saved = out[:]
                    del out[:]
                    emit_block(pre, body)
                    res.extend(out); del out[:]; out.extend(saved)
                    start = j + 1
            j += 1
        return "\n".join(res)

    result = build(css)
    header = ("/* GENERATED by scripts/build_preview_skin.py from survey.css - do not edit by hand.\n"
              "   Survey styles scoped under .survey-skin for the Studio question test view. */\n"
              ".survey-skin{font:15px/1.55 -apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;color:#1a2733}\n"
              ".survey-skin .btn.primary{margin-top:12px}\n"
              ".survey-skin .err.ok{background:#e7f4ec;color:#1a7f4b;border-color:#bfe6d2}\n")
    open(DST, "w", encoding="utf-8").write(header + result + "\n")
    print("wrote", os.path.relpath(DST, ROOT), len(result), "bytes")


if __name__ == "__main__":
    main()
